#!/bin/bash

module load fsl

find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-03 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-03/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-03/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-04 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-04/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-04/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-03 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-03/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-03/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-04 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-04/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-04/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-04 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-04/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-04/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-03 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-03/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-03/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-03 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-03/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-03/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-04 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-04/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-04/bad_files.txt; fi' \;

find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-01 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-01/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-01/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-02 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-02/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-pain_run-02/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-01 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-01/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-01/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-02 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-02/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-post_task-rest_run-02/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-02 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-02/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-02/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-01 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-01/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-rest_run-01/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-01 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-01/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-01/bad_files.txt; fi' \;
find /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-02 \( -name "sub-*_GMWM2ASL_mcf_brain.nii.gz" -exec gunzip {} \; -o -name "sub-*_GMWM2ASL_mcf_brain.nii" \) -exec sh -c 'file="{}"; file_unzipped=$(echo "$file" | sed "s/\.gz$//"); dim4=$(fslinfo "$file_unzipped" | grep "^dim4" | awk "{print \$2}"); if [ "$dim4" -eq "52" ]; then echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-02/file_list.txt; else echo "$file_unzipped" >> /blue/jjtanner/shared/proact/dcm2bids/derivatives/asl/ses-pre_task-pain_run-02/bad_files.txt; fi' \;